---
- name: Add tags to all tasks
  tags:
    - always
  block:
    - name: Configure sshd_config
      ansible.builtin.template:
        src: "{{ sshd_template | default('sshd_config.j2') }}"
        dest: /etc/ssh/sshd_config
      notify: Restart sshd

